### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by avihexims** [arthurmbandeira/nodejs-currency-converter#3]
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Users\AJ\temptProject\Tempt-Project\node_modules\nodejs-currency-converter\index.js:15:24
    at tryCatcher (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:638:18)
    at Request._callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\nodeback.js:45:21)
    at Request.self.callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Users\AJ\temptProject\Tempt-Project\node_modules\nodejs-currency-converter\index.js:15:24
    at tryCatcher (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:638:18)
    at Request._callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\nodeback.js:45:21)
    at Request.self.callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Users\AJ\temptProject\Tempt-Project\node_modules\nodejs-currency-converter\index.js:15:24
    at tryCatcher (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:638:18)
    at Request._callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\nodeback.js:45:21)
    at Request.self.callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Users\AJ\temptProject\Tempt-Project\node_modules\nodejs-currency-converter\index.js:15:24
    at tryCatcher (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\promise.js:638:18)
    at Request._callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\bluebird\js\release\nodeback.js:45:21)
    at Request.self.callback (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (C:\Users\AJ\temptProject\Tempt-Project\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

**Comment by Tobjoern** [comment]
I am facing the same problem with the demo code, which makes the library unusable

```
const currConverter = require('nodejs-currency-converter')

currConverter(1, 'USD', 'BRL').then((response: any) => {
    console.log(response)
});
```
